#!/bin/bash
#
# Script for MAC address spoofing
#
# __author__ = 'bl4ckh0l3'
# __license__ = 'GPL v2'
# __maintainer__ = 'bl4ckh0l3'
# __email__ = 'bl4ckh0l3z@gmail.com'
#

interface=""
macaddr_new=""
interfaces=$(sudo ifconfig | cut -d" " -f1 | sort -u | egrep -v "^$")

echo -e "\nPlease select the interface for the mac address you want to spoof:"
for i in $interfaces;do
    echo -e "  -$i"
done
read interface

echo -e "\nPlease type the mac address you want to spoof (format xx:xx:xx:xx:xx:xx):"
read macaddr_new

macaddr_old=$(sudo ifconfig $interface | egrep -o "([a-zA-Z0-9]{2}:){5}[a-zA-Z0-9]{2}")

echo "Changing your mac address from '$macaddr_old' to '$macaddr_new'"
sudo ifconfig $interface down
sudo ifconfig $interface hw ether $macaddr_new
sudo ifconfig $interface up
